stages:
  data_cleaning:
    cmd: time python src/preprocessing/data_cleaning.py data/raw/lucas.csv.gz data/preprocessed/cleaned_data.csv.gz
    deps:
      - data/raw/lucas.csv.gz
      - src/preprocessing/data_cleaning.py
    outs:
      - data/preprocessed/cleaned_data.csv.gz
  correlation_analysis:
    cmd: >
      time python src/analysing/correlation_analysis.py
      data/preprocessed/cleaned_data.csv.gz
      results/correlation_analysis/soc_percent_correlations.csv
      results/correlation_analysis/correlation_bar_graph.png
      results/correlation_analysis/scatterplot_matrix.png
    deps:
      - data/preprocessed/cleaned_data.csv.gz
      - src/analysing/correlation_analysis.py
    outs:
      - results/correlation_analysis/soc_percent_correlations.csv:
          cache: false
      - results/correlation_analysis/correlation_bar_graph.png:
          cache: false
      - results/correlation_analysis/scatterplot_matrix.png:
          cache: false

