stages:
  data_cleaning:
    cmd: > 
      (time python src/preprocessing/data_cleaning.py
      data/raw/lucas.csv.gz
      data/preprocessed/cleaned_data.csv.gz)
      |& tee logs/data_cleaning.log
    deps:
      - data/raw/lucas.csv.gz
      - src/preprocessing/data_cleaning.py
    outs:
      - data/preprocessed/cleaned_data.csv.gz

  correlation_analysis:
    cmd: >
      (time python src/analysing/correlation_analysis.py
      data/preprocessed/cleaned_data.csv.gz
      results/correlation_analysis/soc_percent_correlations.csv
      results/correlation_analysis/correlation_bar_graph.png
      results/correlation_analysis/scatterplot_matrix.png)
      |& tee logs/correlation_analysis.log
    deps:
      - data/preprocessed/cleaned_data.csv.gz
      - src/analysing/correlation_analysis.py
    outs:
      - results/correlation_analysis/soc_percent_correlations.csv
      - results/correlation_analysis/correlation_bar_graph.png:
          cache: false
      - results/correlation_analysis/scatterplot_matrix.png:
          cache: false

  data_imputation:
    cmd: > 
      (time python src/preprocessing/data_imputation.py
      data/preprocessed/cleaned_data.csv.gz
      data/imputed/imputed_data.csv.gz
      results/data_imputation/missing_value_count.csv)
      |& tee logs/data_imputation.log
    deps:
      - data/preprocessed/cleaned_data.csv.gz
      - src/preprocessing/data_imputation.py
    outs:
      - data/imputed/imputed_data.csv.gz
      - results/data_imputation/missing_value_count.csv

  regression_analysis:
    cmd: >
      (time python src/analysing/regression_analysis.py
      data/imputed/imputed_data.csv.gz
      results/regression_analysis/predictions.csv
      results/regression_analysis/regression_coefficients.csv
      results/regression_analysis/predicted_vs_actual_plot.png
      results/regression_analysis/regression_plot.png
      models/regression_analysis/rf_model.pkl)
      |& tee logs/regression_analysis.log
    deps:
      - data/imputed/imputed_data.csv.gz
      - src/analysing/regression_analysis.py
    outs:
      - results/regression_analysis/predictions.csv
      - results/regression_analysis/regression_coefficients.csv
      - results/regression_analysis/predicted_vs_actual_plot.png:
          cache: false
      - results/regression_analysis/regression_plot.png:
          cache: false
      - models/regression_analysis/rf_model.pkl
  
  permutation_importance:
    cmd: > 
      (time python src/analysing/permutation_importance_analysis.py
      data/imputed/imputed_data.csv.gz
      results/permutation_importance_analysis/permutation_importance.csv
      results/permutation_importance_analysis/permutation_importance.png 
      models/regression_analysis/rf_model.pkl)
      |& tee logs/permutation_importance_analysis.log
    deps:
      - src/analysing/permutation_importance_analysis.py
      - data/imputed/imputed_data.csv.gz
      - models/regression_analysis/rf_model.pkl
    outs:
      - results/permutation_importance_analysis/permutation_importance.csv
      - results/permutation_importance_analysis/permutation_importance.png:
          cache: false

  lasso_regression:
    cmd: >
      (time python src/machine_learning/lasso_regression.py
      data/imputed/imputed_data.csv.gz
      models/lasso_regression/lr_model.pkl
      results/lasso_regression/lasso_coefficients.csv
      results/lasso_regression/lasso_regression_plot.png)
      |& tee logs/lasso_regression.log
    deps:
      - data/imputed/imputed_data.csv.gz
      - src/machine_learning/lasso_regression.py
    outs:
      - models/lasso_regression/lr_model.pkl
      - results/lasso_regression/lasso_coefficients.csv
      - results/lasso_regression/lasso_regression_plot.png:
          cache: false
          
  svm_regression:
    cmd: >
      (time python src/machine_learning/svm_regression.py
      data/imputed/imputed_data.csv.gz
      models/svm_regression/svm_model.pkl
      results/svm_regression/svm_regression_plot.png)
      |& tee logs/svm_regression.log
    deps:
      - data/imputed/imputed_data.csv.gz
      - src/machine_learning/svm_regression.py
    outs:
      - models/svm_regression/svm_model.pkl
      - results/svm_regression/svm_regression_plot.png:
          cache: false

  lgbm_regression:
    cmd: >
      (time python src/machine_learning/lgbm_regression.py
      data/imputed/imputed_data.csv.gz
      models/lgbm_regression/lgbm_model.pkl
      results/lgbm_regression/lgbm_regression_plot.png
      results/lgbm_regression/lgbm_importance_features.csv)
      |& tee logs/lgbm_regression.log
    deps:
      - data/imputed/imputed_data.csv.gz
      - src/machine_learning/lgbm_regression.py
    outs:
      - models/lgbm_regression/lgbm_model.pkl
      - results/lgbm_regression/lgbm_regression_plot.png:
          cache: false
      - results/lgbm_regression/lgbm_importance_features.csv

  mlp_regression:
    cmd: >
      (time python src/deep_learning/mlp_regression.py
      data/imputed/imputed_data.csv.gz
      results/mlp_regression/mlp_regression_plot.png
      models/mlp_regression/mlp_model.h5)
      |& tee logs/mlp_regression.log
    deps:
      - data/imputed/imputed_data.csv.gz
      - src/deep_learning/mlp_regression.py
    outs:
      - models/mlp_regression/mlp_model.h5
      - results/mlp_regression/mlp_regression_plot.png:
          cache: false

  dffn_regression:
    cmd: >
      (time python src/deep_learning/dffn_regression.py
      data/imputed/imputed_data.csv.gz
      results/dffn_regression/dffn_regression_plot.png
      models/dffn_regression/dffn_model.h5)
      |& tee logs/dffn_regression.log
    deps:
      - data/imputed/imputed_data.csv.gz
      - src/deep_learning/dffn_regression.py
    outs:
      - models/dffn_regression/dffn_model.h5
      - results/dffn_regression/dffn_regression_plot.png:
          cache: false
  
  lstm_regression:
    cmd: >
      (time python src/deep_learning/lstm_regression.py
      data/imputed/imputed_data.csv.gz
      results/lstm_regression/lstm_regression_plot.png
      models/lstm_regression/lstm_model.h5)
      |& tee logs/lstm_regression.log
    deps:
      - data/imputed/imputed_data.csv.gz
      - src/deep_learning/lstm_regression.py
    outs:
      - models/lstm_regression/lstm_model.h5
      - results/lstm_regression/lstm_regression_plot.png:
          cache: false

  wide_and_deep_regression:
    cmd: >
      (time python src/deep_learning/wide_and_deep_regression.py
      data/imputed/imputed_data.csv.gz
      results/wide_and_deep_regression/wide_and_deep_regression.png
      models/wide_and_deep_regression/wide_and_deep_model.h5)
      |& tee logs/wide_and_deep_regression.log
    deps:
      - data/imputed/imputed_data.csv.gz
      - src/deep_learning/wide_and_deep_regression.py
    outs:
      - models/wide_and_deep_regression/wide_and_deep_model.h5
      - results/wide_and_deep_regression/wide_and_deep_regression.png:
          cache: false
