name: sanity-check

on:
  push:
    branches:
      - main
      - experiment
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: autobotraos/miniconda3-dvc:latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up DVC
      run: |
        dvc pull

    # Run pre-commit on all files
    - name: Run pre-commit
      run: pre-commit run --all-files

    # Run DVC Repro
    - name: Run DVC Repro
      run: |
        dvc repro
